### ISSUE TITLE
Import Postman files to burp

### ISSUE THREAD

**Issue by brenocss** [tagomaru/burp-extension-postman-integration#8]

**Comment by tagomaru** [comment]
Hi @brenocss 
Could you describe the issue since I'm not sure how you're in trouble?

**Comment by brenocss** [comment]
Just a feature request, would be great if we could import to burp target map a postman json file

**Comment by tagomaru** [comment]
Hi @brenocss 
I don't think it is a necessary feature since you can capture http requests from Postman on Burp after importing the postman file into postman.

What do you think?

**Comment by brenocss** [comment]
it's just that redoing the requests by hand in postman just to send/proxy them to burp is a little boring. It would be more interesting to import everything and start an active/passive scan, autorepeater...

**Comment by tagomaru** [comment]
Hi @brenocss 

I understand what you want now.
However, this extension was developed so that I could avoid pretty boring task of typing request infos into postman by hand.
I'm afraid your request is out of scope of this extension.
But once again, I understand what you want, so I might develop such an extension separately from this Postman Integration.

I appreciate for your undestanding.

**Comment by tagomaru** [comment]
I'm going to close this issue...
